# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ffi-uuid}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Mullis"]
  s.date = %q{2010-10-04}
  s.description = %q{FFI Wrapper for libuuid with extra helpers for common UUID tasks like getting an array of uuids for quicker distribution}
  s.email = %q{michael@mullistechnologies.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "ffi-uuid.gemspec",
     "lib/ffi-uuid.rb",
     "lib/ffi/ffi_uuid_impl.rb",
     "test/helper.rb",
     "test/test_ffi_uuid.rb"
  ]
  s.homepage = %q{http://github.com/mmullis/ffi-uuid}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{FFI Wrapper for libuuidm}
  s.test_files = [
    "test/helper.rb",
     "test/test_ffi_uuid.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

